# Generated by Django 2.0.7 on 2022-09-06 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Telebot_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='Null Value')),
                ('Family_Name', models.TextField()),
                ('Mobile_Number', models.TextField(unique=True)),
                ('Education', models.TextField()),
                ('Field', models.TextField()),
                ('Location', models.TextField()),
                ('Date_Added', models.DateTimeField(verbose_name='date published')),
                ('Status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Removed')], max_length=1)),
            ],
        ),
    ]
